#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODEX_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(cd "$CODEX_DIR/.." && pwd)"
TMP_ROOT="$PROJECT_ROOT/.tmp/repo-intake"
MEMORY_DIR="$CODEX_DIR/memory"

usage() {
  cat <<USAGE
Usage:
  bash .codex/tools/repo-intake-cli.sh <repo-url|local-path> [--name <slug>] [--keep]

Examples:
  bash .codex/tools/repo-intake-cli.sh https://github.com/openai/skills
  bash .codex/tools/repo-intake-cli.sh .tmp/repo-intake/collection-claude-20260414-112445
  bash .codex/tools/repo-intake-cli.sh git@github.com:org/repo.git --name repo-scan
USAGE
}

is_dir_writable() {
  local dir="$1"
  mkdir -p "$dir" 2>/dev/null || return 1
  local probe="$dir/.write_probe_$$"
  if ( : > "$probe" ) 2>/dev/null; then
    rm -f "$probe" 2>/dev/null || true
    return 0
  fi
  return 1
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

SOURCE_INPUT="$1"
shift || true

NAME_OVERRIDE=""
KEEP_CLONE=false

while [ $# -gt 0 ]; do
  case "$1" in
    --name)
      NAME_OVERRIDE="${2:-}"
      shift 2
      ;;
    --keep)
      KEEP_CLONE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9]+#-#g; s#(^-|-$)##g'
}

SOURCE_MODE="remote"
SCAN_DIR=""
CLONE_DIR=""
SOURCE_LABEL="$SOURCE_INPUT"

if [ -d "$SOURCE_INPUT" ]; then
  SOURCE_MODE="local"
  SCAN_DIR="$(cd "$SOURCE_INPUT" && pwd)"
else
  SCAN_DIR=""
fi

repo_basename="$(basename "$SOURCE_INPUT")"
repo_basename="${repo_basename%.git}"
repo_slug="$(slugify "$repo_basename")"
if [ -n "$NAME_OVERRIDE" ]; then
  repo_slug="$(slugify "$NAME_OVERRIDE")"
fi
if [ -z "$repo_slug" ]; then
  repo_slug="repo"
fi

ts="$(date +%Y%m%d-%H%M%S)"
clone_dir="$TMP_ROOT/${repo_slug}-${ts}"

mkdir -p "$TMP_ROOT"

REPORT_ROOT="$MEMORY_DIR"
if ! is_dir_writable "$MEMORY_DIR"; then
  REPORT_ROOT="$TMP_ROOT/reports"
  mkdir -p "$REPORT_ROOT"
  echo "[repo-intake] warning: $MEMORY_DIR is not writable, using fallback: $REPORT_ROOT"
fi

report_file="$REPORT_ROOT/repo_intake_report_${repo_slug}_${ts}.md"

if [ "$SOURCE_MODE" = "remote" ]; then
  echo "[repo-intake] cloning: $SOURCE_INPUT"
  git clone --depth 1 "$SOURCE_INPUT" "$clone_dir" >/dev/null 2>&1
  SCAN_DIR="$clone_dir"
  SOURCE_LABEL="$SOURCE_INPUT"
else
  echo "[repo-intake] scanning local path: $SCAN_DIR"
fi

echo "[repo-intake] scanning repository"

readme_files="$(find "$SCAN_DIR" -maxdepth 2 -type f \( -iname 'readme.md' -o -iname 'readme*' \) | sed "s#^$SCAN_DIR/##" | sort || true)"
ci_files="$(find "$SCAN_DIR/.github/workflows" -maxdepth 1 -type f -name '*.yml' 2>/dev/null | sed "s#^$SCAN_DIR/##" | sort || true)"
manifest_files="$(find "$SCAN_DIR" -maxdepth 3 -type f \( -name 'package.json' -o -name 'pnpm-workspace.yaml' -o -name 'pyproject.toml' -o -name 'requirements.txt' -o -name 'Cargo.toml' -o -name 'go.mod' -o -name 'Dockerfile' -o -name 'docker-compose.yml' -o -name '.mcp.json' -o -name 'mcp.json' \) | sed "s#^$SCAN_DIR/##" | sort || true)"
agent_files="$(find "$SCAN_DIR" -maxdepth 4 -type f \( -name 'AGENTS.md' -o -name 'CLAUDE.md' -o -path '*/.codex/*' -o -path '*/.cursor/*' \) | sed "s#^$SCAN_DIR/##" | sort || true)"
skill_files="$(find "$SCAN_DIR" -maxdepth 5 -type f -name 'SKILL.md' | sed "s#^$SCAN_DIR/##" | sort || true)"

skill_count="0"
if [ -n "$skill_files" ]; then
  skill_count="$(echo "$skill_files" | grep -c . || true)"
fi

cat > "$report_file" <<REPORT
---
name: repo-intake-${repo_slug}-${ts}
description: Raw intake report generated by repo-intake CLI for ${SOURCE_LABEL}
type: reference
---

## Source
- Input: ${SOURCE_LABEL}
- Mode: ${SOURCE_MODE}
- Cloned at: ${ts}
- Working path: ${SCAN_DIR}

## Quick Signals
- SKILL.md count: ${skill_count}

## README Files
$(if [ -n "$readme_files" ]; then echo "$readme_files" | sed 's/^/- /'; else echo "- (none found)"; fi)

## CI Workflows
$(if [ -n "$ci_files" ]; then echo "$ci_files" | sed 's/^/- /'; else echo "- (none found)"; fi)

## Build/Runtime Manifests
$(if [ -n "$manifest_files" ]; then echo "$manifest_files" | sed 's/^/- /'; else echo "- (none found)"; fi)

## Agent/Instruction Files
$(if [ -n "$agent_files" ]; then echo "$agent_files" | sed 's/^/- /'; else echo "- (none found)"; fi)

## Skill Files (sample)
$(if [ -n "$skill_files" ]; then echo "$skill_files" | head -n 40 | sed 's/^/- /'; else echo "- (none found)"; fi)

## Next Step for Agent
Use this report as intake evidence, then curate only high-signal patterns into:
- .codex/skills/*
- .codex/README.md
<<<<<<< HEAD
- .codex/memory/akp2i_projects.md
=======
- .codex/memory/MEMORY.md
>>>>>>> origin/main
REPORT

if [ "$KEEP_CLONE" = false ]; then
  if [ "$SOURCE_MODE" = "remote" ]; then
    rm -rf "$clone_dir"
    clone_state="deleted"
  else
    clone_state="kept (local source path)"
  fi
else
  if [ "$SOURCE_MODE" = "remote" ]; then
    clone_state="kept"
  else
    clone_state="kept (local source path)"
  fi
fi

echo "[repo-intake] report: $report_file"
echo "[repo-intake] clone: $clone_state"
if [ "$REPORT_ROOT" != "$MEMORY_DIR" ]; then
  echo "[repo-intake] sync later when writable:"
  echo "  cp \"$report_file\" \"$MEMORY_DIR/\""
fi
